// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikclgmlzbrqubiaulaep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrY2xnbWx6YnJxdWJpYXVsYWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODY4ODksImV4cCI6MjA2OTM2Mjg4OX0.NImVt4HDx700rUEjZjpG8ccdLcBTQxVsxpY1cKlXcEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});